title: mnrst
description: クラウドエンジニアの検証生活
theme: minima
lang: ja
google_analytics: G-9H171CX9NV
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: classic
header_pages:
  - about.md
minima:
  date_format: "%Y年%m月%d日"
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/mnrst" }
    - { platform: twitter, user_url: "https://twitter.com/stmnr" }
