title: mnrst
description: クラウドエンジニアの検証生活
theme: minima
lang: ja
google_analytics: G-9H171CX9NV
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
header_pages:
  - about.md
minima:
  skin: classic
  date_format: "%Y年%m月%d日"
paginate: 10
paginate_path: "page:num"
show_excerpts: false
